[project]
name = "streaming-sem-topk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "litellm>=1.80.9",
    "lotus-ai>=1.1.4",
    "pandas>=2.3.3",
    "tqdm>=4.67.1",
]
